---
ci:
  skip: [terraform_docs, terraform-fmt, terraform-validate, tflint, terragrunt-hclfmt]

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict
      - id: no-commit-to-branch
      - id: check-yaml
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_docs
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.11
    hooks:
      - id: terraform-fmt
      - id: terragrunt-hclfmt
      - id: terraform-validate
        files: ^examples/
      - id: tflint
        files: ^examples/
        exclude: .*/README\.md
      - id: gofmt
        files: ^test/
      - id: golint
        files: ^test/

  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.5
    hooks:
      - id: add-msg-issue-prefix

#  - repo: https://github.com/radix-ai/auto-smart-commit
#    rev: v1.0.2
#    hooks:
#      - id: auto-smart-commit

#  - repo: https://github.com/commitizen-tools/commitizen
#    rev: v2.14.0
#    hooks:
#      - id: commitizen
#        stages: [commit-msg]
