name: Terragrunt example workflow

on:
  push:
    branches:
      - AP-1

jobs:
  IaC:
    name: Terragrunt Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.28.4
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          fileOutput: ','
      - name: Get Base Folder
        run: |
          ls -la $HOME/
          cat $HOME/files.csv
      - name: Terragrunt Validate
        run: terragrunt run-all validate
      - name: Terragrunt Plan
        run: terragrunt run-all plan
